// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etqvicgjyqrbtemofjpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0cXZpY2dqeXFyYnRlbW9manB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4OTAxODAsImV4cCI6MjA2ODQ2NjE4MH0.GVMpkhXd2ZgwpxpmHmHFVNrukVuMfavKQyCyC8cGXVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});